#!/bin/bash

# This scripts sets autoconnect priority for wifi BSSIDs
# each argument is expected to be a BSSID, the first the highest priority

# We set priorities from (n+10) to 11
counter=10

# Counting the number of arguments
for var in "$@"
do
 #echo "  "$var
 counter=$((counter+1))
done

for var in "$@"
do
  echo "Setting $var as priority $counter"
  set -x
  nmcli connection modify $var connection.autoconnect-priority $counter
  set +x
  echo ""
  counter=$((counter-1))
done
exit 0
